/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package caso

import viewmodel.PedidoViewModel
import model.*

class App {
    val greeting: String
        get() {
            return "Owow"
        }
}

fun main() {
    val viewModel = PedidoViewModel()

    // Mostrar pedidos iniciales
    println("Pedidos iniciales:")
    viewModel.mostrarPedidos()

    // Intentar confirmar un pedido (debería funcionar si hay existencias)
    println("\nIntentando confirmar el pedido 1:")
    viewModel.confirmarPedido(1)

    // Intentar confirmar otro pedido
    println("\nIntentando confirmar el pedido 2:")
    viewModel.confirmarPedido(2)

    // Registrar un pago parcial para el pedido 1
    val pago1 = Pago(10.0, MetodoPago.Efectivo("USD"))
    viewModel.registrarPago(1, pago1)

    // Registrar otro pago para completar el total
    val pago2 = Pago(8.08, MetodoPago.TarjetaCredito("1234567890123456", "12/24", "VISA"))
    viewModel.registrarPago(1, pago2)

    viewModel.mostrarPedidos()
}
