/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package caso

import viewmodel.PedidoViewModel
import model.*

class App {
    val greeting: String
        get() {
            return "Owow"
        }
}

fun main() {
    val viewModel = PedidoViewModel()

    // Mostrar pedidos iniciales
    println("Pedidos iniciales:")
    viewModel.mostrarPedidos()

    // Actualizar el estado de un pedido
    viewModel.actualizarEstadoPedido(1, EstadoPedido.PAGADO)
    println("\nEstado del pedido 1 actualizado:")
    viewModel.mostrarPedidos()

    // Cambiar método de pago
    viewModel.cambiarMetodoPago(1, MetodoPago.TarjetaCredito("1234567890123456", "12/24", "VISA"))
    println("\nMétodo de pago del pedido 1 cambiado:")
    viewModel.mostrarPedidos()
}
